In [1]:
import numpy as np
from keras.preprocessing.text import one_hot
from keras.preprocessing import sequence
from keras import models
from keras import layers

Using TensorFlow backend.


In [2]:
docs = ['Well done!',
       'Good work',
       'Great effort',
       'nice work',
       'Excellent!',
       'Weak',
       'Poor effort',
       'not good',
       'poor work',
       'Could have done better']
labels = np.array([1,1,1,1,1,0,0,0,0,0])


In [3]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[9, 19], [32, 7], [2, 3], [43, 7], [44], [5], [12, 3], [14, 32], [12, 7], [19, 1, 19, 2]]


In [4]:
max_length = 4
padded_docs = sequence.pad_sequences(encoded_docs, maxlen = max_length,padding='post')
print(padded_docs)

[[ 9 19  0  0]
 [32  7  0  0]
 [ 2  3  0  0]
 [43  7  0  0]
 [44  0  0  0]
 [ 5  0  0  0]
 [12  3  0  0]
 [14 32  0  0]
 [12  7  0  0]
 [19  1 19  2]]


In [5]:
model = models.Sequential()
model.add(layers.Embedding(vocab_size, 8, input_length=max_length))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation = 'sigmoid'))

W0821 11:19:50.410838 11904 deprecation_wrapper.py:119] From C:\Users\Affinity\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0821 11:19:50.451833 11904 deprecation_wrapper.py:119] From C:\Users\Affinity\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0821 11:19:50.460318 11904 deprecation_wrapper.py:119] From C:\Users\Affinity\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [10]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['acc'])
print(model.summary())

W0821 11:21:26.737270 11904 deprecation_wrapper.py:119] From C:\Users\Affinity\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0821 11:21:26.755599 11904 deprecation_wrapper.py:119] From C:\Users\Affinity\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0821 11:21:26.759580 11904 deprecation.py:323] From C:\Users\Affinity\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
model.fit(padded_docs, labels, epochs = 50, verbose=0)

W0821 11:21:29.745287 11904 deprecation_wrapper.py:119] From C:\Users\Affinity\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



In [12]:
loss, accuracy = model.evaluate(padded_docs, labels, verbose =0)
print('Accuracy : %f', (accuracy*100))

Accuracy : %f 89.99999761581421
